server:
  port: 9090
  servlet:
    contextPath: /batchdemo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username:
    password:
    hikari:
      idleTimeout: 10000
      minimum-idle: 0
      connectionTimeout: 60000
      maximumPoolSize: 20
      max-lifetime: 60000
      leak-detection-threshold: 60000
  jpa:
#    showSql: true
  batch:
    initializeSchema: never
    job:
      enabled: false

logging:
  level:
    root: INFO

async:
  coreSize: 100
  maxSize: 100

reader:
  pageSize: 10000

job:
  gridSize: 10